name: Build devtools
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '12'
        
      - name: Build
        run: |
          npm install
          npm run build
          
      - name: Export artifacts
        uses: actions/upload-artifact@v2
        with:
          name: devtools
          path: dist/*
